spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JudySpace
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      write_dates_as_timestamps: false
  jpa:
    show-sql: true

logging:
  level:
    root: INFO
  file:
    name: logs/app.log